### ISSUE TITLE
usertest

### ISSUE THREAD

**Issue by yujing-student** [yujing-student/component-building-block#21]
<h1>vragen</h1>

is de pagina duidelijk?

zijn er verbeterpunten ?

**Comment by yujing-student** [comment]
<h1>de usertest</h1>

de pagina was duidelijk ze begon bij het invullen van het form en drukte op submit
toen kwam ze op de not found pagina en dat begreep ze niet omdat ze alle pagina's had ingevuld dus er mist nog feedback waardoor de gebruiker weet dat het formulier ogerkomen is

**Comment by aliceafanasieva** [comment]
**Is de pagina duidelijk?**
De component is duidelijk, ik vind de layout van de formulier heel netjes ontworpen.
Met sterretjes was duidelijk aangegeven welke velden verplicht zijn en waar je moet klikken om formulier te verzenden. 

**Zijn er verbeterpunten?**

Misschien kan jij de padding in de button rondom de tekst "schrijf mij in" uitlijnen, want aan de linkerkant zit er meer ruimte. En er is volgens mij een overbodige bodemlijn onder de pijl. 

<img width="192" alt="image" src="https://github.com/user-attachments/assets/02c3ae7c-6fec-42a3-944d-de7c74a548ab">

Verder echt heel goed bezig, mooie component!

**Comment by yujing-student** [comment]
<h1>dit heb ik opgelost </h1>

Je feedback heb ik toegepast

![Image](https://github.com/user-attachments/assets/dfe6f38e-545d-41c8-849a-fec4987cfd00)
