### ISSUE TITLE
Feedback visuele hiërarchie

### ISSUE THREAD

**Issue by Annevd** [yujing-student/component-building-block#22]
### Variatie 1
<img width=400 src="https://github.com/user-attachments/assets/7bcdb8e6-1fbd-452e-9db0-4761d8abcba2">

De visuele hiërarchie is heer heel duidelijk door de grote en dikgedrukte titel.

### Variatie 3

<img width=400 src="https://github.com/user-attachments/assets/acd90f19-15fc-429d-8af6-22371747a063">

Hier hetzelfde als variatie 1.

### Variatie 2

<img width=400 src="https://github.com/user-attachments/assets/ccdc6712-cd7c-4ce0-85af-f86e21aae924">

De titel is hier vergeleken met de andere variaties veel minder opvallend, wat de andere variaties gelijk al beter maakt dan deze.

### Variatie 4

<img width=400 src="https://github.com/user-attachments/assets/523580c1-c1fb-4da7-a350-7ca7238822ef">

Hier zijn de dikgedrukte placeholders erg opvallend. Sommige placeholders zijn wel dikgedrukt, en sommige niet. Hierdoor is deze variatie inconsistent en zijn de andere variaties waar alles normale diktes zijn fijner om naar te kijken.

**Comment by yujing-student** [comment]
De feedback heb ik verwerkt in variatie 10  als zero state

![image](https://github.com/user-attachments/assets/80fc0ab5-f68f-4229-b066-10e8030b9ee2)


Dit is de successtate

![image](https://github.com/user-attachments/assets/dc9de27e-4ae2-4dce-a4b9-113c34055940)

dit is de error state

als iets niet ingevuld is of verkeerd

![image](https://github.com/user-attachments/assets/49fd0799-9c4a-48f3-83d4-e49b8fa3631a)


hier is de livelink

https://www.figma.com/design/42reO3hhIYuIIRIxwdmX5Q/schets-sprint-16-component?node-id=8-438&m=dev&t=3ku9bOWv5TvHJmom-1
