### ISSUE TITLE
Verzenden zonder iets ingevuld te hebben

### ISSUE THREAD

**Issue by Annevd** [yujing-student/component-building-block#24]
Ik heb getest of ik het formulier kon verzenden zonder de verplichte velden te hebben ingevuld. Ik werd doorgeleid naar een bedankt pagina met een 404.

![image](https://github.com/user-attachments/assets/b967bd22-3831-47ce-a277-a1bb9c8ff54a)

Probeer nog is te kijken of je er voor kan zorgen dat ik niet op de knop kan klikken totdat alle verplichte velden ingevuld zijn. Dit zorgt ervoor dat er geen halve/foute formulieren verzonden zullen worden.

**Comment by yujing-student** [comment]
dit heb ik opgelost door een bedankt pagina te maken 

![image](https://github.com/user-attachments/assets/9f2c63e0-1666-4853-af68-8377819c3dda)
