### ISSUE TITLE
is een fieldset hier nodig?

### ISSUE THREAD

**Issue by wingsvn** [yujing-student/component-building-block#26]
https://github.com/yujing-student/component-building-block/blob/750fc4d3405939d8d12f6aab662c5d4a813e11ae/src/lib/Form.svelte#L10-L90

**Comment by yujing-student** [comment]
ja want anders kreeg ik met een container query de 2 kolommen niet naast elkaar
met de fieldset stijl ik de input fields dit vond ik een betere oplossing dan een div en op het form de styling zetten werkt niet


zie hier de permalink
https://github.com/yujing-student/component-building-block/blob/685db48dd437a1c9daf82bc1a67f4858cf417e8f/src/lib/Form.svelte#L242-L264
