### ISSUE TITLE
design accessibility: valid & invalid states

### ISSUE THREAD

**Issue by wingsvn** [yujing-student/component-building-block#27]
![image](https://github.com/user-attachments/assets/5d44439f-ff26-4d36-8296-ef830119329e)

De valid en invalid states van je form geven een groene/rode lijn, maar dit is best dun en niet voor iedereen zichtbaar, vooral met de zwarte lijn er boven. Misschien kun je nog even kijk hoe je dat anders kan doen om de toegankelijkheid te verbeteren.

**Comment by yujing-student** [comment]
<h1>dit heb ik opgelost</h1>

![image](https://github.com/user-attachments/assets/58679dc2-4268-4cd4-aeb8-a9940b3f85cf)

Met outline word er styling toegepast op het element en niet de border bottom waardoor de ui state beter zichtbaar is

```
outline: 2px solid green;
```
```
  outline: 2px solid red;
    
```
