### ISSUE TITLE
indentatie & spacing

### ISSUE THREAD

**Issue by wingsvn** [yujing-student/component-building-block#28]
https://github.com/yujing-student/component-building-block/blob/750fc4d3405939d8d12f6aab662c5d4a813e11ae/src/lib/Form.svelte#L93-L103
https://github.com/yujing-student/component-building-block/blob/750fc4d3405939d8d12f6aab662c5d4a813e11ae/src/lib/Form.svelte#L32-L49

let nog even op je wit ruimte in je code ;)

**Comment by yujing-student** [comment]
<h1>dit heb ik toegepepast</h1>

hier heb ik alles onder elkaar gezet

https://github.com/yujing-student/component-building-block/blob/685db48dd437a1c9daf82bc1a67f4858cf417e8f/src/lib/Form.svelte#L17-L92

en hier heb ik dat ook gedaan

https://github.com/yujing-student/component-building-block/blob/685db48dd437a1c9daf82bc1a67f4858cf417e8f/src/lib/Form.svelte#L151-L172
